notification:
  email:
    on_success: never
    on_failure: never
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
    - lib32z1
    - lib32ncurses5
    - oracle-java8-installer
  sonarcloud:
    branches:
      - master
    organization: "joshua27-github"
    token:
      secure: $SONAR_TOKEN
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - ./gradlew --stacktrace -Pheadless=true check
  - sonar-scanner
after_success:
  - ./gradlew distZip winZip createApp